version: '3'
services:
  node:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '5000:2204'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
